/bin/sh compatibility, formatting

diff --git a/iremove b/iremove
--- a/iremove
+++ b/iremove
@@ -7,33 +7,32 @@
 
 LABEL=
 VOLUME=
-VOLUMES=`ls -1 /dev/disk0s1s* | sort -V`
+VOLUMES=$(ls -1 /dev/disk0s1s* | sort -V)
 
 # Might as well leave this.
-if [[ -z $VOLUMES ]]; then
-	echo "Can't find any apfs volumes. Something is very wrong."
+if [ -z "$VOLUMES" ]; then
+	echo "Can't find any apfs volumes. Something is very wrong." 1>&2
 	exit 1
 fi
 
 # Search for android volume
-for i in ${VOLUMES}; do
-	LABEL=`/System/Library/Filesystems/apfs.fs/apfs.util -p $i`
-	if [ "${LABEL}" == "Android" ]; then
+for i in $VOLUMES; do
+	LABEL=$(/System/Library/Filesystems/apfs.fs/apfs.util -p "$i")
+	if [ "$LABEL" = "Android" ]; then
 		VOLUME=$i
 		break
 	fi
 done
-if [ ! -b ${VOLUME} ]; then
+if [ ! -b "$VOLUME" ]; then
 	echo "Cannot find Android volume. You probably haven't installed sandcastle."
 	exit 0
 fi
 
 
-echo "Mounting ${VOLUME}"
+echo "Mounting $VOLUME"
 mkdir -p /tmp/mnt
-mount -t apfs ${VOLUME} /tmp/mnt 
-if [ $? -ne 0 ]; then
-	echo "Failed to mount volume. Are you running as root?";
+if ! mount -t apfs "$VOLUME" /tmp/mnt; then
+	echo "Failed to mount volume. Are you running as root?" 1>&2
 	exit 1
 fi
 
@@ -48,7 +47,7 @@ fi
 if [ -e /tmp/mnt/Library ]; then
 	echo "Either you did something incredibly strange with partitions or something is very wrong."
 	umount /tmp/mnt
-	echo "Unmounted /tmp/mnt"
+	echo "Unmounted /tmp/mnt" 1>&2
 	exit 1
 fi
 
@@ -60,7 +59,7 @@ fi
 
 echo -n "This will free about 2gb. Are you sure you want to delete all Android files? (type yes to continue): "
 read -r CONFIRM
-if [ ! "$CONFIRM" == "yes" ]; then
+if [ ! "$CONFIRM" = "yes" ]; then
 	umount /tmp/mnt
 	echo "Unmounted /tmp/mnt"
 	exit 0
diff --git a/isetup b/isetup
--- a/isetup
+++ b/isetup
@@ -7,23 +7,23 @@
 
 LABEL=
 VOLUME=
-VOLUMES=`ls -1 /dev/disk0s1s* | sort -V`
+VOLUMES=$(ls -1 /dev/disk0s1s* | sort -V)
 
 # I can't find any way to delete accidentally created apfs volumes. This should help prevent making them in the first place.
-if [[ -z $VOLUMES ]]; then
-	echo "Can't find any apfs volumes. Something is very wrong."
+if [ -z "$VOLUMES" ]; then
+	echo "Can't find any apfs volumes. Something is very wrong." 1>&2
 	exit 1
 fi
 
 # Search for android volume
-for i in ${VOLUMES}; do
-	LABEL=`/System/Library/Filesystems/apfs.fs/apfs.util -p $i`
-	if [ "${LABEL}" == "Android" ]; then
+for i in $VOLUMES; do
+	LABEL=$(/System/Library/Filesystems/apfs.fs/apfs.util -p "$i")
+	if [ "$LABEL" = "Android" ]; then
 		VOLUME=$i
 		break;
 	fi
 done
-if [ ! -b ${VOLUME} ]; then
+if [ ! -b "$VOLUME" ]; then
 	echo "Creating new Android volume"
 	newfs_apfs -A -v Android -e /dev/disk0s1
 fi
@@ -33,27 +33,26 @@ fi
 
 LABEL=
 VOLUME=
-VOLUMES=`ls /dev/disk0s1s* | sort -V`
+VOLUMES=$(ls /dev/disk0s1s* | sort -V)
 
-for i in ${VOLUMES}; do
-	LABEL=`/System/Library/Filesystems/apfs.fs/apfs.util -p $i`
-	if [ "${LABEL}" == "Android" ]; then
+for i in $VOLUMES; do
+	LABEL=$(/System/Library/Filesystems/apfs.fs/apfs.util -p "$i")
+	if [ "$LABEL" = "Android" ]; then
 		VOLUME=$i
 		break;
 	fi
 done
-if [ ! -b ${VOLUME} ]; then 
-	echo "Android volume not found. This should have been caught earlier"
+if [ ! -b "$VOLUME" ]; then
+	echo "Android volume not found. This should have been caught earlier" 1>&2
 	exit 1
 fi
 
 
 
-echo "Mounting ${VOLUME}"
+echo "Mounting $VOLUME"
 mkdir -p /tmp/mnt
-mount -t apfs ${VOLUME} /tmp/mnt 
-if [ $? -ne 0 ]; then
-	echo "Failed to mount volume. Are you running as root?";
+if ! mount -t apfs "$VOLUME" /tmp/mnt; then
+	echo "Failed to mount volume. Are you running as root?" 1>&2
 	exit 1
 fi
 
@@ -64,15 +63,14 @@ else
 	echo "Starting download of the nand file. This will take a few minutes"
 	wget http://assets.checkra.in/downloads/sandcastle/88b1089d97fe72ab77af8253ab7c312f8e789d49209234239be2408c3ad89a34/nand.gz -O /tmp/mnt/nand.gz
 	if [ $? -ne 0 ]; then
-		echo "Failed to download nand. Are you connected to wifi?"
+		echo "Failed to download nand. Are you connected to wifi?" 1>&2
 		umount /tmp/mnt
 		echo "unmounted /tmp/mnt"
 		exit 1
 	fi
 	echo "Decompressing nand image"
-	gunzip -d /tmp/mnt/nand.gz
-	if [ $? -ne 0 ]; then
-		echo "Failed to decompress nand. Network interrupted? gzip not installed?"
+	if ! gunzip -d /tmp/mnt/nand.gz; then
+		echo "Failed to decompress nand. Network interrupted? gzip not installed?" 1>&2
 		umount /tmp/mnt
 		echo "unmounted /tmp/mnt"
 		exit 1
@@ -83,7 +81,7 @@ fi
 echo "Applying touchscreen/WiFi patch and copying driver files."
 
 # The Hack.
-echo -n "  " | dd bs=1 seek=1145078249 count=2 status=none conv=notrunc of=/tmp/mnt/nand
+echo "  " | dd bs=1 seek=1145078249 count=2 status=none conv=notrunc of=/tmp/mnt/nand
 
 # The Fix.
 mkdir -p /tmp/mnt/usr/share/firmware/
